spring:
  application:
    name: springboot-cloud-zipkin
  main:
    allow-bean-definition-overriding: true
#zipkin 端口
server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false