spring:
  application:
    name: springboot-cloud-web-admin-ribbon
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  #zipkin链路追踪
  zipkin:
    base-url: http://localhost:9411
  #服务监控
  boot:
    admin:
      client:
        url: http://localhost:8084
server:
  port: 8764

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/