spring:
  application:
    name: springboot-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: http://47.100.223.188/lcdiao/springboot-cloud-config.git
          search-paths: respo
          username: 120879566@qq.com
          password: asd52342
  #zipkin链路追踪
  zipkin:
    base-url: http://localhost:9411
  #服务监控
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
