spring:
  application:
    name: springboot-cloud-service-admin
  #zipkin链路追踪
  zipkin:
    base-url: http://localhost:9411
  #服务监控
  boot:
    admin:
      client:
        url: http://localhost:8084
server:
  port: 8763
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
