spring:
  application:
    name: springboot-cloud-zuul
  main:
    allow-bean-definition-overriding: true
  #zipkin链路追踪
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: springboot-cloud-web-admin-ribbon
    api-b:
      path: /api/b/**
      serviceId: springboot-cloud-web-admin-feign
